### ISSUE TITLE
留言 | 博採眾長

### ISSUE THREAD

**Issue by Lruihao** [Lruihao/lruihao.github.io#53]
https://lruihao.github.io/guestbook/

**Comment by Lruihao** [comment]
这是github的地址

**Comment by Lruihao** [comment]
http://lruihao.cn
https://www.lruihao.cn
https://lruihao.github.io
http://liruihao.coding.me
每个地址的评论阅读数据不共享

**Comment by Lruihao** [comment]
**欢迎大家留言关照！**

**Comment by xeahsoon** [comment]
sitemap 是怎么生成的鸭

**Comment by Lruihao** [comment]
> sitemap 是怎么生成的鸭

1. hexo-generator-baidu-sitemap
2. hexo-generator-sitemap
